name: EC2 Rollback

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for the rollback'
        required: true
        default: 'Manual Trigger'
  repository_dispatch:
    types: [rollback-trigger]
    
jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read input.json and set variables
        id: read_json
        run: |
          echo "Reading input.json..."
          INSTANCE_ID=$(jq -r '.instance_id' input.json)
          echo "INSTANCE_ID=${INSTANCE_ID}" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install boto3

      - name: Download Rollback Data from S3
        run: |
          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/rollback/${INSTANCE_ID}_rollback.json rollback.json

      - name: Perform Rollback
        run: python scripts/rollback_instance.py
        env:
          ROLLBACK_FILE_PATH: rollback.json
