name: Trigger Approval

on:
  workflow_run:
    workflows: ["EC2 Analysis and Recomendation"]
    types:
      - completed

jobs:
  trigger_manual_approval_workflow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Manual Approval Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'manual_approval.yml',
              ref: 'main',
              inputs: {
                approval_status: 'approved' // Or 'rejected', 'override'
              }
            });
